[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build --workspace=@betteam/web"]

[start]
cmd = "npx serve apps/web/dist -p $PORT --listen 0.0.0.0"
